workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: never
    - when: always

variables:
  # VERSION env-var is referenced in build.gradle.kts  to set the version of the jar artifact
  VERSION: "1.0.${CI_PIPELINE_IID}"
  JAR_NAME: "wh-kafka-connect-jslt-transform-${VERSION}.jar"


build-lib:
  stage: build
  image: gradle:7.4-jdk11-alpine
  interruptible: true
  rules:
    - when: always
  cache:
    key: "wh-kafka-connect-jslt-transform"
    paths:
      - build
      - .gradle/wrapper
      - .gradle/caches
      - .m2/repository
  artifacts:
    when: always
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
    paths:
      - build/libs/${JAR_NAME}
    expire_in: 1 week
  script:
    - gradle build

deploy-to-nexus:
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
  stage: deploy
  image: gradle:7.4-jdk11-alpine
  interruptible: true
  cache:
    key: "wh-kafka-connect-jslt-transform"
    paths:
      - build
      - .gradle/wrapper
      - .gradle/caches
      - .m2/repository
  script:
    - gradle publish
